pipeline {
    agent any
    parameters {
        string (name: 'branch', defaultValue: 'main', description: 'some info')
    }
    stages {
        stage ("SCM") {
            steps{
                git branch: '${params.branch}', url: 'https://github.com/venkyscafe/Hello-Parallel.git'
            }
        }
        stage ("List all Environment Variables") {
            steps {
                script {
                    echo "List all Environment Variables"
                    sh '''
                    echo "List all Environment Variables"
                    echo "=============================="
                    printenv | sort
                    '''
                }
            }
        }
    }
}