pipeline {
    agent any
    parameters {
        text (name: 'Text', defaultValue: 'Please Enter Your Project Description')
        booleanParam (name: 'Admin', defaultValue: false, description: 'Are you an Admin?')
        choice (name: 'Choice', choices: ['Banana', 'Apple'], description: 'Selected Choice')
    }
    stages {
        stage ("pre-flight") {
            steps {
                echo "Text: ${params.Text}"
                echo "Admin user? ${params.Admin ? 'Yes' : 'No'}"
                echo "Selected Choice: ${params.Choice}"
            }
        }
    }
}