pipeline {
    agent any
    parameters {
        text (name: 'Enter-Project-Details', defaultValue: 'Please Enter Your Porject Description')
        booleanParam (name: 'is-Admin', defaultValue: false, description: 'Are you an Admin?')
        choice (name: 'Select-your-Choice', choices: ['Banana', 'Apple'], description: 'Selected Choice')
    }
    stages {
        stage ("pre-flight") {
            steps {
                echo "Text: ${params.Enter-Project-Details}"
                echo "Admin user? ${params.is-Admin ? 'Yes' : 'No'}"
                echo "Selected Choice: ${params.Select-your-Choice}"
            }
        }
    }
}