pipeline {
    agent any
    stages {
        stage ("Decrypting file") {
            steps {
                script {
                    try {
                        echo "Decrypting file.."
                        throw new Exception ("Decryption Failed")
                        echo "Decryption Success !!"
                    } catch (Exception e) {
                        echo "Deleting Incomplete File : ${e.message}"
                        // throw e
                    } finally {
                        echo "Deleting File"
                    }
                }
            }
        }
        stage ("ELT") {
            steps {
                script {
                    try {
                        echo "ELT starting.."
                        echo "Checking Decryption Status"
                        echo "Loading file to DB"
                        //throw new Exception ("DB Connection Failed")
                        echo "ELT Success !!"
                    } catch (Exception e) {
                        echo "Deleting Incomplete File : ${e.message}"
                        throw e
                    } finally {
                        echo "Deleting Workspace"
                    }
                }
            }
        }
    }

    post {
        failure {
            echo "Pipeline Failed"
            echo "Sending Failed Alert"
        }
        success {
            echo "Pipeline Success"
            echo "Sending Success Alert"
        }
    }
}