pipeline {
    
    agent any
    
    parameters {
        string (name: 'branch', defaultValue: 'main', description: 'some info')
    }

    environment {
        WORDS = "I AM A WORDS HUMAN"
        SWORDS = "I-AM-A-SWORDS-HUMAN"
    }

    stages {
        stage ("SCM") {
            steps {
                git branch: "${params.branch}", url: 'https://github.com/venkyscafe/Hello-Parallel.git'
            }
        }

        stage ("Static Analysis") {
            steps {
                echo "Perform Static Analysis"
                sleep time: 3, unit: 'SECONDS'
                script {
                    def words = env.WORDS.split(' ')
                    for (word in words) {
                        echo "SA"+word
                    }
                }
            }
        }

        stage ("Build") {
            steps {
                echo "Build the code"
                sleep time: 3, unit: 'SECONDS'
                script {
                    def swords = env.SWORDS.split('-')
                    for (sword in swords) {
                        echo "B"+sword
                    }
                }
            }
        }

        stage ("Unit Test") {
            steps {
                echo "Execute Unit Testing"
                sleep time: 3, unit: 'SECONDS'
                script {
                    def words = env.WORDS.split(' ')
                    for (word in words) {
                        echo "UT"+word
                    }
                }
            }
        }

        stage ("Package") {
            steps {
                echo "Package the code for release"
            }
        }
    }
}