pipeline {
    agent any
    stages {
        stage ("Build") {
            steps {
                echo "Build the code"
            }
        }
        stage ("Notification") {
            steps {
                echo "Send Slack Notification"
                slackSend channel: 'devops', message: 'Build completed'
            }
        }
    }
}